version: "3.5"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file: './.env'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  cardservice:
    build:
      context: ./cardservice
      dockerfile: Dockerfile
    env_file: './.env'
    environment:
      - PORT=80
      - DATASOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db
  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    env_file: './.env'
    environment:
      - PORT=80
      - DATASOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
volumes:
  db-data:
