name: Cardset Workflow
on:
  push:
    branches:
    - master
    paths:
    - cardservice
jobs:
  runs-on: self-hosted
  deploy:
    - name: Rebuild docker-compose -> cardservice
      run: docker-compose up cardservice -d --build
