name: Authservice Workflow
on:
  push:
    branches:
      - master
    paths:
      - authservice
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up go 1.21.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        working-directory: authservice
        run: go build
      - name: Test
        working-directory: authservice
        run: go test -v ./...