name: Frontend Workflow
on:
  push:
    branches:
      - master
    paths:
      - frontend
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.2.0'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build
        working-directory: frontend
        run: npm run build
      - name: Lint
        working-directory: frontend
        run: npm run lint -- --max-warnings 50
      # todo: prettier